---

- name: Install software-properties-common
  apt: name=software-properties-common state=present

- name: Download NodeJS installation setup script
  get_url:
    url: https://deb.nodesource.com/setup_7.x
    dest: /tmp/nodejs_setup.sh
    mode: 0744

- name: Run NodeJS setup script
  shell: /tmp/nodejs_setup.sh
  become: yes
  args:
    executable: /bin/bash

- name: Install NodeJS
  become: yes
  apt: name=nodejs=7.* state=present

- name: Clone sm-graphql git repository
  git: >
    dest={{ sm_graphql_home }}
    repo=https://github.com/METASPACE2020/sm-graphql.git
    update=yes
    version={{ sm_graphql_branch }}

- name: Install sm-graphql dependencies
  shell: npm install
  args:
    chdir: "{{ sm_graphql_home }}"
    executable: /bin/bash

- name: Pull config from the remote host
  fetch: src={{ sm_graphql_home }}/config.js.template dest=/tmp/config.js.template
         flat=yes fail_on_missing=yes

- name: Save config as ./config.js
  template: src=/tmp/config.js.template dest={{ sm_graphql_home }}/config.js
            owner=ubuntu group=ubuntu mode=0600

- name: Create a folder for isotopic images
  file:
    path: /opt/data/sm_data/public/
    state: directory
    mode: 0755
