- name: installing web app dependencies as miniconda distribution
  hosts: sm-vbox
  remote_user: ubuntu
  
  roles:
    - role: miniconda
      miniconda_version: latest
      miniconda_python: 2
      miniconda_prefix: /opt/dev/miniconda
      miniconda_env:
        name: sm
        dependencies:
          - python=2
          - numpy=1.10
          - scipy=0.16
          - matplotlib=1.5
          - pandas=0.18
          - cffi
          - pip:
            - pyMSpec
            - cpyMSpec
            - pyImagingMSpec
            - cpyImagingMSpec
            - requests
            - mock
            - psycopg2
            - py4j
            - pyimzML
            - pytest
            - tornado
            - tornpsql
            - recommonmark
            - boto3
            - networkx
            - fabric
