- name: getting sm code and setting up
  hosts: sm-vbox
  remote_user: ubuntu

  roles:
    - role: sm
      sm_branch: master
      postgres_sm_password: "1234"
      venv: "/opt/dev/miniconda"
      conda_env: "sm"
      spark_home: "/usr/lib/spark"
      sm_home: "/opt/dev/sm"
