---

dependencies:
  - role: base
    become: yes

  - role: postgres
    become: yes

  - role: elasticsearch
    become: yes

  - role: kibana
    become: yes

  - role: nginx
    become: yes

  - role: miniconda

  - role: supervisor
