---

- name: Deploying SM platform components
  hosts: sm-vbox
  user: ubuntu

  vars_files:
    - ../vars/graphql.yml
    - ../vars/web_app.yml

  vars:
    sm_web_app_url: "{{ sm_webapp_url }}"

  tasks:
    - include: ../deploy_tasks/graphql.yml
    - include: ../deploy_tasks/mol_db.yml
    - include: ../deploy_tasks/sm_api.yml
    - include: ../deploy_tasks/web_app.yml
