---

- name: Deploying SM engine code
  hosts: sm-vbox
  user: ubuntu
  gather_facts: false

  tasks:
    - include: ../engine_deploy_tasks.yml


- name: Deploying SM web app code
  hosts: sm-vbox
  user: ubuntu
  gather_facts: false

  tasks:
    - include: ../web_app_deploy_tasks.yml
