---

- name: Installing Postgres
  hosts: sm-vbox
  user: ubuntu
  become: yes

  roles:
    - role: postgres


- name: Installing SM dependencies as miniconda distribution
  hosts: sm-vbox
  user: ubuntu

  roles:
    - role: miniconda


- name: Installing SM web app
  hosts: sm-vbox
  user: ubuntu

  roles:
    - role: sm_webapp
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"


- name: Installing SM engine
  hosts: sm-vbox
  user: ubuntu

  roles:
    - role: sm_spark_master
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
      spark_usr_dir: "{{ spark_home }}"
      spark_env_extras: "{{ spark_env_extras_master }}"
