---

- name: Set up SM services
  hosts: sm-vbox
  user: ubuntu

  vars_files:
    - ../vars/sm_api.yml

  roles:
    - role: postgres
      become: yes

    - role: elasticsearch
      become: yes

    - role: kibana
      become: yes

    - role: nginx

    - role: rabbitmq

    - role: miniconda

    - role: supervisor

    - role: mol_db

    - role: sm_api

    - role: nodejs

    - role: sm_graphql

    - role: sm_web_app


- name: Set up SM engine
  hosts: sm-vbox
  user: ubuntu

  vars_files:
    - ../vars/sm_spark_master.yml

  vars:
    spark_master_host: local[*]
    spark_slave_ips: [localhost]

  roles:
    - role: spark
      become: yes
      spark_env_extras: "{{ spark_env_extras_master }}"

    - role: spark_master
      become: yes

    - role: sm_spark_master
