---

- name: Set up SM services
  hosts: sm-vbox
  user: ubuntu

  roles:
    - role: postgres
      become: yes
      tags: [postgres]

    - role: elasticsearch
      become: yes
      tags: [elasticsearch]

    - role: kibana
      become: yes

    - role: nginx
      tags: [nginx]

    - role: rabbitmq

    - role: miniconda
      tags: [miniconda]

    - role: supervisor

    - role: mol_db
      tags: [mol_db]

    - role: sm_api
      tags: [sm_api]

    - role: nodejs
      tags: [nodejs]

    - role: sm_graphql
      tags: [sm_graphql]

    - role: sm_web_app


- name: Set up SM engine
  hosts: sm-vbox
  user: ubuntu

  vars:
    spark_master_host: local[*]
    spark_slave_ips: [localhost]

  roles:
    - role: spark
      become: yes
      spark_env_extras: "{{ spark_env_extras_master }}"

    - role: spark_master
      become: yes

    - role: sm_spark_master
  tags: [sm-engine]
