---

- name: Set up SM services
  hosts: sm-vbox
  user: ubuntu

  roles:
    - role: postgres
      become: yes
      tags: [postgres]

    - role: elasticsearch
      become: yes

    - role: kibana
      become: yes

    - role: nginx
      tags: [nginx]

    - role: rabbitmq

    - role: miniconda
      tags: [miniconda]

    - role: supervisor

    - role: mol_db
      tags: [mol_db]

    - role: sm_api

    - role: nodejs

    - role: sm_graphql

    - role: sm_web_app


- name: Set up SM engine
  hosts: sm-vbox
  user: ubuntu

  vars:
    spark_master_host: local[*]
    spark_slave_ips: [localhost]
    venv: "{{ miniconda_prefix }}"
    conda_env: "{{ miniconda_env.name }}"
    spark_usr_dir: "{{ spark_home }}"
    sm_web_app_url: "{{ sm_webapp_url }}"
    es_host: "{{ sm_es_host }}"
    es_port: "{{ sm_es_port }}"
    es_user: "{{ sm_es_user }}"
    es_password: "{{ sm_es_password }}"

  roles:
    - role: spark
      become: yes
      spark_env_extras: "{{ spark_env_extras_master }}"

    - role: spark_master
      become: yes

    - role: sm_spark_master
      tags: [sm_spark_master]
