---

- name: SM services instance basic configuration
  hosts: web
  user: ubuntu
  gather_facts: no

  roles:
    - role: base
      become: yes


- name: SM services instance configuration
  hosts: web
  user: ubuntu
  gather_facts: yes

  vars:
    kibana_version: "{{ elasticsearch_version }}"
    venv: "{{ miniconda_prefix }}"
    conda_env: "{{ miniconda_env.name }}"

  roles:
    - role: postgres
      become: yes

    - role: elasticsearch
      become: yes

    - role: kibana
      become: yes
      es_port: 9200

    - role: nginx
      become: yes
      nginx_vhosts:
        - listen: 8080
          auth_basic: yes
          proxy_pass_port: 5601
        - listen: 80
          proxy_pass_port: 8082
        - listen: "{{ es_port }}"
          auth_basic: yes
          proxy_pass_port: 9200
      basic_auth_users:
        - user: "{{ es_user }}"
          password: "{{ es_password }}"
        - user: "{{ kibana_user }}"
          password: "{{ kibana_password }}"

    - role: rabbitmq

    - role: miniconda

    - role: supervisor

    - role: mol_db
      mol_db_home: "{{ sm_mol_db_home }}"
      mol_db_postgres_pass: "{{ sm_postgres_password }}"
      miniconda_env:
        name: mol_db

    - role: sm_api
      sm_web_app_url: "{{ sm_mol_db_url }}"

    - role: nodejs

    - role: sm_graphql
      sm_database_password: "{{ sm_postgres_password }}"
      slack_webhook_url: "{{ sm_graphql_slack_webhook_url }}"
      slack_channel: "{{ sm_graphql_slack_channel }}"
      jwt_secret: "{{ sm_graphql_jwt_secret }}"
      mol_image_host: "{{ sm_graphql_mol_image_host }}"

    - role: sm_web_app
      port: "{{ sm_webapp_port }}"
      cookie_secret: "{{ sm_webapp_cookie_secret }}"
      jwt_secret: "{{ sm_graphql_jwt_secret }}"
      admin_emails: "{{ sm_webapp_admin_emails }}"
      aws_access_key_id: "{{ sm_webapp_aws_access_key_id }}"
      aws_secret_access_key: "{{ sm_webapp_aws_secret_access_key }}"
      s3_bucket: "{{ sm_webapp_s3_bucket }}"
      graphql_url: "{{ sm_graphql_public_url }}"
      hostname: "{{ sm_webapp_hostname }}"
      google_client_id: "{{ sm_webapp_google_client_id }}"
      google_client_secret: "{{ sm_webapp_google_client_secret }}"
      google_callback_url: "http://{{ sm_webapp_hostname }}/auth/google/callback"

    - role: sm_cluster_autostart
