---

- name: SM services instance basic configuration
  hosts: web
  user: ubuntu
  gather_facts: no

  roles:
    - role: base
      become: yes


- name: SM services instance configuration
  hosts: web
  user: ubuntu
  gather_facts: yes

  vars_files:
    - ../../vars/sm_api.yml

  roles:
    - role: postgres
      become: yes

    - role: elasticsearch
      become: yes

    - role: kibana
      become: yes

    - role: nginx

    - role: rabbitmq

    - role: miniconda

    - role: supervisor

    - role: mol_db
      tags: [mol_db]

    - role: sm_api

    - role: nodejs

    - role: sm_graphql

    - role: sm_web_app

    - role: sm_cluster_autostart
