---

- name: SM services instance basic configuration
  hosts: web
  user: ubuntu
  gather_facts: no

  roles:
    - role: base
      become: yes


- name: SM services instance configuration
  hosts: web
  user: ubuntu
  gather_facts: yes

  vars_files:
    - ../vars/web_app.yml
    - ../vars/graphql.yml

  vars:
    kibana_version: "{{ elasticsearch_version }}"
    venv: "{{ miniconda_prefix }}"
    conda_env: "{{ miniconda_env.name }}"

  roles:
    - role: postgres
      become: yes

    - role: elasticsearch
      become: yes
      elasticsearch_port: "{{ es_port }}"

    - role: kibana
      become: yes
      es_port: 9200

    - role: nginx

    - role: rabbitmq

    - role: miniconda

    - role: supervisor

    - role: mol_db
      mol_db_home: "{{ sm_mol_db_home }}"
      mol_db_postgres_pass: "{{ sm_postgres_password }}"
      miniconda_env:
        name: mol_db

    - role: sm_api
      sm_web_app_url: "{{ sm_mol_db_url }}"

    - role: nodejs

    - role: sm_graphql

    - role: sm_web_app

    - role: sm_cluster_autostart
