---

- name: SM services instance basic configuration
  hosts: web
  user: ubuntu
  gather_facts: no

  roles:
    - role: base
      become: yes


- name: SM services instance configuration
  hosts: web
  user: ubuntu
  gather_facts: yes

  vars:
    elasticsearch_port: "{{ es_port }}"
    kibana_version: "{{ elasticsearch_version }}"
    nginx_vhosts:
      - listen: 8080
        auth_basic: yes
        proxy_pass_port: 5601
      - listen: 80
        proxy_pass_port: 8082
    venv: "{{ miniconda_prefix }}"
    conda_env: "{{ miniconda_env.name }}"

  roles:
    - role: postgres
      become: yes

    - role: elasticsearch
      become: yes

    - role: kibana
      become: yes

    - role: nginx
      become: yes

    - role: miniconda

    - role: supervisor

    - role: mol_db
      mol_db_postgres_pass: "{{ sm_postgres_password }}"
      miniconda_env:
        name: mol_db

    - role: sm_api

    - role: nodejs

    - role: sm_graphql
      sm_database_password: "{{ sm_postgres_password }}"
      slack_webhook_url: "{{ sm_graphql_slack_webhook_url }}"
      slack_channel: "{{ sm_graphql_slack_channel }}"
      jwt_secret: "{{ sm_graphql_jwt_secret }}"

    - role: sm_web_app
      port: "{{ sm_webapp_port }}"
      cookie_secret: "{{ sm_webapp_cookie_secret }}"
      jwt_secret: "{{ sm_graphql_jwt_secret }}"
      admin_emails: "{{ sm_webapp_admin_emails }}"
      aws_access_key_id: "{{ sm_webapp_aws_access_key_id }}"
      aws_secret_access_key: "{{ sm_webapp_aws_secret_access_key }}"
      s3_bucket: "{{ sm_webapp_s3_bucket }}"
      graphql_url: "{{ sm_graphql_public_url }}"
