- name: Install sys libs needed for Ansible
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - libffi-dev
    - libssl-dev

- name: Install Ansible
  pip: name=ansible

- name: Install sm-cluster-autostart dependencies
  pip: name={{ item }} state=latest
  with_items:
    - pika
    - requests
    - pyyaml
    - fabric
    - boto3

- name: Make sure {{ sm_ansible_home }} exists
  become: yes
  file: path={{ sm_ansible_home }} owner=ubuntu group=ubuntu state=directory mode=0755

- name: Git clone sm-engine-ansible
  git:
    dest: "{{ sm_ansible_home }}"
    repo: "{{ sm_ansible_url }}"
    update: yes
    version: "{{ sm_ansbile_branch }}"

- name: Make sure {{ sm_ansible_home }}/aws/logs exists
  become: yes
  file: path={{ sm_ansible_home }}/aws/logs owner=ubuntu group=ubuntu state=directory mode=0755

- name: Templated supervisord config for the cluster_auto_start_daemon
  template: src=sm-cluster-autostart-daemon.supervisor.j2
            dest=/etc/supervisor/sm-cluster-autostart-daemon.supervisor
            owner=ubuntu group=ubuntu mode=0600

- name: Copy private key for SSHing to the masters
  copy: src={{ spark_key_file }} dest="/home/ubuntu/.ssh/id_rsa" owner=ubuntu group=ubuntu mode="u=rw,g=,o="
