---

- name: ec2.py module cache cleaning
  hosts: localhost
  connection: local

  tasks:
    - name: Drop cached aws api responses created by ec2.py
      shell: rm ~/.ansible/tmp/*.cache
#      when: aws_api_cache_clean
