---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    component: ''

  tasks:
    - name: Spinning up SM cluster instances
      shell: python manage_instances.py start {{ component }}
