---

- name: Spinning up AWS instances
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    components: ''

  tasks:
#    - debug: var=components
#    - debug: var=aws_key_name
#
#    - name: Spin up SM cluster instances
#      shell: python aws_instance_manager.py start --key-name {{ aws_key_name }} --components {{ components }}
#      when: spark_volume_size is not defined
#
#    - name: Spin up SM cluster instances for creating a new AMI
#      shell: python aws_instance_manager.py start --key-name {{ aws_key_name }} --components {{ components }} --spark-volume-size {{ spark_volume_size }}
#      when: spark_volume_size is defined
#
#    - name: Wait for instances to become available
#      pause: seconds=20
#
#    - name: Update the inventory file
#      shell: python update_inventory.py
