---

- name: SM web app instance configuration
  hosts: tag_hostgroup_sm_webserver_aws
  user: ubuntu
  gather_facts: true

  roles:
    - role: common
      become: yes

    - role: postgres
      become: yes

    - role: miniconda

    - role: sm_webapp
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
