---

- name: Collect Spark master facts for AMI creating
  hosts: master
  user: ubuntu

  tasks:
    - name: Gather AWS instance facts
      action: ec2_facts


- name: Create new Spark master AMI
  hosts: localhost

  tasks:
    - debug: var=ansible_date_time.iso8601
    - debug: var=hostvars['master'].ansible_ec2_instance_id

    - name: Create AMI
      ec2_ami:
        name: sm-spark-master-{{ ansible_date_time.iso8601 | regex_replace(':', '-')  }}
        instance_id: "{{ hostvars['master'].ansible_ec2_instance_id }}"
        tags: {"hostgroup": "{{ cluster_configuration.instances.master.hostgroup}}" }
        wait: yes
      register: instance

    - debug: var=instance


- name: Create new Spark slave AMI
  hosts: slave
  user: ubuntu
