---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    component: ''
    key_name: ''

  tasks:
    - debug: var=component
    - debug: var=key_name

    - name: Spinning up SM cluster instances
      shell: python manage_instances.py start {{ component }} {{ key_name }}
