---

- include: aws_clean_cache.yml


- name: Spinning up AWS instances
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    component: ''

  tasks:
    - debug: var=component
    - debug: var=aws_key_name
    - debug: var=hostgroups

    - name: Spin up SM cluster instances
      shell: python aws_instance_manager.py start {{ component }} {{ aws_key_name }}
