---

- name: SM spark slave instances configuration
  hosts: tag_hostgroup_sm_spark_slave
  user: ubuntu
  gather_facts: true

  roles:
    - role: sm_spark_slave
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
      spark_usr_dir: "{{ spark_home }}"
      spark_env_extras: "{{ spark_env_extras_slave }}"
      block_dev_labels: "{{ block_dev_labels_slave }}"
  tags: ["slave"]


- name: SM spark master instance configuration
  hosts: tag_hostgroup_sm_spark_master
  user: ubuntu
  gather_facts: true

  vars:
    spark_slave_ips: []
    postgres_host: "{{ groups.get('tag_hostgroup_sm_webserver', ['localhost'])[0] }}"

  pre_tasks:
    - name: Create a list of private ip addresses for the slave instances
      set_fact: spark_slave_ips="{{ spark_slave_ips  + [ hostvars[item].ec2_private_ip_address ] }}"
      with_items: "{{ groups['tag_hostgroup_sm_spark_slave'] }}"

  roles:
    - role: sm_spark_master
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
      spark_usr_dir: "{{ spark_home }}"
      spark_env_extras: "{{ spark_env_extras_master }}"
  tags: ["master"]
