---

- name: SM web app instance configuration
  hosts: tag_hostgroup_sm_webserver
  user: ubuntu
  gather_facts: true

  roles:
    - role: sm_webapp
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
