---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    component: ''
    key_name: ''

  tasks:
    - name: Stopping SM cluster instances
      shell: python manage_instances.py stop {{ component }} {{ key_name }}
