---

- name: SM web app instance configuration
  hosts: tag_group_sm_webapp_aws
  user: ubuntu
  gather_facts: true

  roles:
    - role: postgres
      become: yes

    - role: miniconda

    - role: sm_webapp
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"

#- name: SM spark master instance configuration
#  hosts: tag_group_sm_spark_master_aws
#  user: ubuntu
#  gather_facts: true
#
#  roles:
#    - role: sm_spark_master
#      spark_usr_dir: "{{ spark_home }}"
#      venv: "{{ miniconda_prefix }}"
#      conda_env: "{{ miniconda_env.name }}"
