---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: intsco_embl_aws
    ami_id: ami-f9a62c8a  # ubuntu 14.04, ebs-only instance

  tasks:
    - name: Spinning up a web server instance
      ec2:
         key_name: "{{ key_name }}"
         group: "sm web app"
         instance_type: t2.micro
         image: "{{ ami_id }}"
         wait: true
         exact_count: 1
         count_tag: group=sm_webserver_aws
         instance_tags: group=sm_webserver_aws Name=sm_webserver
      register: ec2

    - name: associate elastic ip address with the webserver instance
      ec2_eip: device_id=ec2.instances[0].id ip={{ webserver_ip }}

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: See ec2.instances
      debug: var=ec2.instances

    - name: Spinning up an SM spark master instance
      ec2:
         key_name: "{{ key_name }}"
         group: default
         instance_type: t2.small
         image: "{{ ami_id }}"
         wait: true
         exact_count: 1
         count_tag: group=sm_spark_master_aws
         instance_tags: group=sm_spark_master_aws Name=sm_master
      register: ec2

    - name: associate elastic ip address with the spark master instance
      ec2_eip: device_id=ec2.instances[0].id ip={{ master_ip }}

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: See ec2.instances
      debug: var=ec2.instances
