---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    component: ''

  tasks:
    - name: Stopping SM cluster instances
      shell: python aws_instance_manager.py stop {{ component }} {{ aws_key_name }}
