---

- name: SM spark slave instances configuration
  hosts: slave
  user: ubuntu
  gather_facts: yes

#  pre_tasks:
#    - name: Gather facts about the slave instances
#      setup:

  roles:
    - role: sm_spark_slave
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
      spark_usr_dir: "{{ spark_home }}"
      spark_env_extras: "{{ spark_env_extras_slave }}"
      block_dev_labels: "{{ block_dev_labels_slave }}"
  tags: ["slave"]


- name: SM spark master instance configuration
  hosts: master
  user: ubuntu
  gather_facts: no

  vars:
    spark_master_host: "spark://{{ ansible_hostname }}:7077"
    spark_slave_ips: []

  pre_tasks:
    - name: Run apt-get update
      become: yes
      raw: apt-get update

    - name: Install python-simplejson
      become: yes
      raw: apt-get install -y python-simplejson

    - name: Gather facts about the master instance
      setup:

    - name: Create a list of private ip addresses for the slave instances
      set_fact: spark_slave_ips="{{ spark_slave_ips  + [ hostvars[item].ansible_ssh_host ] }}"
      with_items: "{{ groups['slave'] }}"

  roles:
    - role: sm_spark_master
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
      spark_usr_dir: "{{ spark_home }}"
      spark_env_extras: "{{ spark_env_extras_master }}"
  tags: ["master"]
