---

aws_region: eu-central-1
aws_key_name: iprotsyuk_lcms_sm_eu_central_1

miniconda_prefix: /opt/dev/miniconda3
miniconda_env:
  name: sm

cluster_configuration:
  instances:
    web:
      hostgroup: sm-web-lcms-dev

    master:
      hostgroup: sm-master-lcms-dev
      type: c4.large
      n: 1
      elipalloc:
      price: 0.6
      sec_group: default
      image:

      block_dev_maps:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20
            DeleteOnTermination: True
            VolumeType: gp2

    slave:
      hostgroup: sm-slave-lcms-dev
      type: c4.large
      n: 1
      elipalloc:
      price: 0.6
      sec_group: default
      image:

      block_dev_maps:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20
            DeleteOnTermination: True
            VolumeType: gp2
