---

- name: Deploying cluster-auto-start
  hosts: queue
  user: ubuntu
  gather_facts: false

  vars:
    activate_venv: "true" # fake shell command

  tasks:
    - name: Git clone sm-engine-ansible
      git:
        dest: "{{ sm_ansible_home }}"
        repo: "{{ sm_ansible_url }}"
        update: yes
        version: "{{ sm_ansible_branch }}"

    - name: Upload templated group_vars/all.yml
      template: src={{ stage }}/group_vars/all.yml dest={{ sm_ansible_home }}/aws/{{ stage }}/group_vars/all.yml
                owner=ubuntu group=ubuntu mode=0600

    - name: Update the inventory file
      local_action: command python update_inventory.py --stage {{ stage }}

    - name: Copy inventory file
      copy: src={{ stage }}/hosts dest={{ sm_ansible_home }}/aws/{{ stage }} mode=0600 owner=ubuntu group=ubuntu

    - include: ../restart_supervisor.yml
