---

- name: Deploying SM engine code to the slaves
  hosts: slave
  user: ubuntu
  gather_facts: false

  tasks:
    - include: ../../deploy_tasks/engine.yml
  tags: [slave]


- name: Deploying SM engine code to the master
  hosts: master
  user: ubuntu
  gather_facts: true

  vars_files:
    - ../../vars/engine.yml

  tasks:
    - include: ../../deploy_tasks/engine.yml

    - name: Pull SM config from the remote host
      fetch: src={{ sm_home }}/conf/config.json.template dest=/tmp/config.json.template
             flat=yes fail_on_missing=yes

    - name: "Put SM config to {{ sm_home }}/conf/config.json"
      template: src=/tmp/config.json.template dest={{ sm_home }}/conf/config.json
                owner={{ spark_user }} group={{ spark_user }} mode=0600

    - name: Remove old logs
      file: path="{{ sm_home }}/logs" state=absent

    - name: Create folder for logs
      file: path="{{ sm_home }}/logs" state=directory

    - name: Restart Filebeat to avoid issues with old logs
      become: yes
      systemd: name=filebeat state=restarted

    - include: ../../restart_supervisor.yml supervisor_app=sm-daemon
  tags: [master]
