---

- name: Deploying SM web app code
  user: ubuntu
  hosts: web

  tasks:
    - name: Clone sm-web-app git repository
      git:
        dest: "{{ sm_webapp_home }}"
        repo: https://github.com/METASPACE2020/sm-webapp.git
        update: yes
        force: yes
        recursive: yes
        version: "{{ sm_webapp_branch }}"
      register: git_deploy
      until: git_deploy | succeeded

    - name: Install sm-web-app dependencies
      shell: npm install
      args:
        chdir: "{{ sm_webapp_home }}"
        executable: /bin/bash

    - name: Dereference metadata schema
      shell: node deref_schema.js > src/assets/metadata_schema.json
      args:
        chdir: "{{ sm_webapp_home }}"
        executable: /bin/bash

    - name: Run build app
      shell: npm run build
      args:
        chdir: "{{ sm_webapp_home }}"
        executable: /bin/bash

    - include: ../../restart_supervisor.yml supervisor_app=sm-web-app
