---

- name: Deploying SM services code
  user: ubuntu
  hosts: web

  tasks:
    - name: Gather EC2 instance facts
      ec2_metadata_facts:
      tags: [always]

    - import_tasks: ../../deploy_tasks/sm_mol_db.yml
      tags: [sm_mol_db]

    - import_tasks: ../../deploy_tasks/sm_api.yml
      tags: [sm_api]

    - import_tasks: ../../deploy_tasks/sm_graphql.yml
      tags: [sm_graphql]

    - import_tasks: ../../deploy_tasks/sm_web_app.yml
      tags: [sm_web_app]

    - import_tasks: ../../deploy_tasks/sm_cluster_autostart.yml
      tags: [sm_cluster_autostart]
