---

filebeat_config:
  filebeat:
    prospectors: "{{ spark_master_filebeat_prospectors }}"

  output:
    elasticsearch:
      hosts: ["{{ elk_private_ip }}:9200"]
      pipeline: "{{ spark_master_elk_es_ingest_node_pipeline_id }}"
      #protocol: "https"
      username: "{{ elk_es_user }}"
      password: "{{ elk_es_password }}"

ingest_node_pipelines:
  - description: "Ingest node description for the sm engine log messages"
    processors:
      - grok:
          field: "message"
          patterns:
            - "%{TIMESTAMP_ISO8601:timestamp} - %{LOGLEVEL:level} - %{NOTSPACE:component} - %{NOTSPACE:file_line} -%{GREEDYDATA:msg}"
          ignore_missing: true
      - date:
          field: "timestamp"
          formats:
            - "yyyy-MM-dd HH:mm:ss,SSS"
