---

bound_to_any_host: false
kibana_version: "{{ elk_version }}"
elasticsearch_version: "{{ elk_version }}"

nginx_config: |
  server {
      listen 80;

      server_name {{ nginx_server_name }};

      location / {
          proxy_pass http://localhost:5601;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
      }
  }
